// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfffoGl2eXVzgQK9ZIjSfjmnnnRQR5vS8',
    appId: '1:266624432519:web:5c26826f58210b3f67bb22',
    messagingSenderId: '266624432519',
    projectId: 'quan-ly-nha-hang-20f37',
    authDomain: 'quan-ly-nha-hang-20f37.firebaseapp.com',
    storageBucket: 'quan-ly-nha-hang-20f37.firebasestorage.app',
    measurementId: 'G-9871FSY824',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-AHafsF-75PYAH6JPzEw47FzzNIsvJAk',
    appId: '1:266624432519:android:f31b06df96910cf667bb22',
    messagingSenderId: '266624432519',
    projectId: 'quan-ly-nha-hang-20f37',
    storageBucket: 'quan-ly-nha-hang-20f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiRt52hg7CY66knZgFp0XXQHCVk5LUPTE',
    appId: '1:266624432519:ios:f991f4c7147e6e4d67bb22',
    messagingSenderId: '266624432519',
    projectId: 'quan-ly-nha-hang-20f37',
    storageBucket: 'quan-ly-nha-hang-20f37.firebasestorage.app',
    iosBundleId: 'com.example.quanlynhahang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiRt52hg7CY66knZgFp0XXQHCVk5LUPTE',
    appId: '1:266624432519:ios:f991f4c7147e6e4d67bb22',
    messagingSenderId: '266624432519',
    projectId: 'quan-ly-nha-hang-20f37',
    storageBucket: 'quan-ly-nha-hang-20f37.firebasestorage.app',
    iosBundleId: 'com.example.quanlynhahang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfffoGl2eXVzgQK9ZIjSfjmnnnRQR5vS8',
    appId: '1:266624432519:web:b119b6f0293092f667bb22',
    messagingSenderId: '266624432519',
    projectId: 'quan-ly-nha-hang-20f37',
    authDomain: 'quan-ly-nha-hang-20f37.firebaseapp.com',
    storageBucket: 'quan-ly-nha-hang-20f37.firebasestorage.app',
    measurementId: 'G-NFRW8C575P',
  );
}
